---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/contact
  label: Contact
  create: all
  match: "**/*"
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*"
- type: directory
  path: content/wp-content
  label: Wp content
  create: all
  match: "**/*"
- type: directory
  path: content/services
  label: Services
  create: all
  match: "**/*"
- type: directory
  path: content/wpforms-preview
  label: Wpforms preview
  create: all
  match: "**/*"
- type: directory
  path: content/about-me
  label: About me
  create: all
  match: "**/*"
- type: directory
  path: content/home
  label: Home
  create: all
  match: "**/*"
- type: directory
  path: content/daron-obrien-digital-marketing-specialist
  label: Daron obrien digital marketing specialist
  create: all
  match: "**/*"
- type: directory
  path: content/portfolio
  label: Portfolio
  create: all
  match: "**/*"
- type: directory
  path: content/stories
  label: Stories
  create: all
  match: "**/*"
- type: directory
  path: content/privacy-policy
  label: Privacy policy
  create: all
  match: "**/*"
- type: directory
  path: content/portfolio-grid
  label: Portfolio grid
  create: all
  match: "**/*"
- type: directory
  path: content/my-work
  label: My work
  create: all
  match: "**/*"
- type: directory
  path: content/resume
  label: Resume
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.46'
